variable "identifier" {
  description = "DB instance identifier, e.g. \"dev-postgres\"."
  type        = string

  validation {
    condition     = can(regex("^[a-z][a-z0-9-]{0,62}$", var.identifier))
    error_message = "identifier must start with a lowercase letter and contain only lowercase letters, digits and hyphens."
  }
}

variable "engine" {
  description = "Database engine: postgres or mysql."
  type        = string
  default     = "postgres"

  validation {
    condition     = contains(["postgres", "mysql"], var.engine)
    error_message = "engine must be postgres or mysql."
  }
}

variable "engine_version" {
  description = "Engine version, e.g. \"16.4\" for PostgreSQL or \"8.0.39\" for MySQL."
  type        = string
}

variable "family" {
  description = "Parameter group family, e.g. \"postgres16\" or \"mysql8.0\". Must match engine_version's major — a mismatch is rejected at apply, not at plan."
  type        = string
}

variable "major_engine_version" {
  description = "Major engine version for the option group, e.g. \"16\" or \"8.0\"."
  type        = string
}

variable "instance_class" {
  description = "Instance class, e.g. \"db.t4g.medium\". Burstable t-classes are fine for dev; production should use an m or r class so the workload is not silently throttled when CPU credits run out."
  type        = string
  default     = "db.t4g.medium"
}

variable "db_subnet_group_name" {
  description = "DB subnet group. From module.vpc.database_subnet_group_name. Those subnets have no internet gateway route and no NAT route, so the database has no path to or from the internet regardless of what a security group says."
  type        = string
}

variable "security_group_ids" {
  description = "Security groups for the instance. From module.security_groups.rds_sg_id, which allows the database port from the application tiers and nothing else."
  type        = list(string)

  validation {
    condition     = length(var.security_group_ids) > 0
    error_message = "At least one security group is required."
  }
}

variable "multi_az" {
  description = "Run a synchronous standby in a second AZ with automatic failover. This is the difference between an AZ failure being a failover and being an outage; it roughly doubles instance cost."
  type        = bool
  default     = false
}

variable "port" {
  description = "Database port. Null uses the engine default: 5432 for PostgreSQL, 3306 for MySQL. Must match the security-groups module's database_port."
  type        = number
  default     = null
}

variable "allocated_storage" {
  description = "Initial storage in GiB."
  type        = number
  default     = 50
}

variable "max_allocated_storage" {
  description = "Ceiling for storage autoscaling in GiB. Set above allocated_storage to enable it; 0 disables autoscaling, which means a full disk is an outage."
  type        = number
  default     = 200
}

variable "storage_type" {
  description = "Storage type: gp3, gp2 or io1."
  type        = string
  default     = "gp3"
}

variable "kms_key_arn" {
  description = <<-EOT
    KMS key encrypting storage, automated backups, read replicas and snapshots.

    Storage encryption cannot be turned on or changed after the instance is
    created — the only path is a snapshot, a restore into a new encrypted
    instance and a cutover. Get this right at creation.
  EOT
  type        = string
  default     = null
}

variable "db_name" {
  description = "Name of the initial database created inside the instance."
  type        = string
  default     = null
}

variable "username" {
  description = "Master username. Not a secret on its own; the password is generated by AWS and stored in Secrets Manager."
  type        = string
  default     = "dbadmin"
}

variable "master_user_secret_kms_key_arn" {
  description = "KMS key encrypting the AWS-managed master user secret. Null uses the default Secrets Manager key."
  type        = string
  default     = null
}

variable "backup_retention_period" {
  description = "Days of automated backups. 0 disables backups entirely and also disables point-in-time recovery — never correct outside a throwaway environment."
  type        = number
  default     = 7

  validation {
    condition     = var.backup_retention_period >= 0 && var.backup_retention_period <= 35
    error_message = "backup_retention_period must be between 0 and 35 days."
  }
}

variable "backup_window" {
  description = "Daily backup window in UTC, e.g. \"03:00-04:00\"."
  type        = string
  default     = "03:00-04:00"
}

variable "maintenance_window" {
  description = "Weekly maintenance window in UTC, e.g. \"Mon:04:00-Mon:05:00\". Must not overlap backup_window."
  type        = string
  default     = "Mon:04:00-Mon:05:00"
}

variable "copy_tags_to_snapshot" {
  description = "Copy instance tags onto snapshots, so a snapshot can still be attributed to an environment and a cost centre after the instance is gone."
  type        = bool
  default     = true
}

variable "deletion_protection" {
  description = "Refuse to delete the instance until this is turned off. On in production — it is the last thing standing between a mistargeted destroy and the data."
  type        = bool
  default     = false
}

variable "skip_final_snapshot" {
  description = "Skip the final snapshot on deletion. True makes deletion irreversible; leave false anywhere the data matters."
  type        = bool
  default     = false
}

variable "delete_automated_backups" {
  description = "Delete automated backups when the instance is deleted."
  type        = bool
  default     = false
}

variable "monitoring_interval" {
  description = "Enhanced Monitoring granularity in seconds: 0, 1, 5, 10, 15, 30 or 60. 0 disables it. Anything other than 0 requires monitoring_role_arn."
  type        = number
  default     = 60

  validation {
    condition     = contains([0, 1, 5, 10, 15, 30, 60], var.monitoring_interval)
    error_message = "monitoring_interval must be 0, 1, 5, 10, 15, 30 or 60."
  }
}

variable "monitoring_role_arn" {
  description = "Role RDS assumes for Enhanced Monitoring. From module.iam.rds_monitoring_role_arn."
  type        = string
  default     = null
}

variable "performance_insights_enabled" {
  description = "Enable Performance Insights. This is what turns \"the database is slow\" into a specific query; the 7-day tier is free."
  type        = bool
  default     = true
}

variable "performance_insights_retention_period" {
  description = "Performance Insights retention in days: 7 (free), or 31-month multiples up to 731."
  type        = number
  default     = 7
}

variable "performance_insights_kms_key_arn" {
  description = "KMS key for Performance Insights data."
  type        = string
  default     = null
}

variable "enabled_cloudwatch_logs_exports" {
  description = "Log types published to CloudWatch. Null picks the engine defaults: postgresql+upgrade for PostgreSQL, error+general+slowquery for MySQL."
  type        = list(string)
  default     = null
}

variable "cloudwatch_log_group_retention_in_days" {
  description = "Retention for the exported log groups."
  type        = number
  default     = 30
}

variable "parameters" {
  description = "DB parameter group parameters. Null applies the module's engine defaults, which force TLS on connections."
  type = list(object({
    name         = string
    value        = string
    apply_method = optional(string, "immediate")
  }))
  default = null
}

variable "auto_minor_version_upgrade" {
  description = "Let AWS apply minor version upgrades in the maintenance window."
  type        = bool
  default     = true
}

variable "apply_immediately" {
  description = "Apply modifications now instead of in the maintenance window. True can cause an immediate restart — leave false in production."
  type        = bool
  default     = false
}

variable "ca_cert_identifier" {
  description = "RDS CA bundle for the server certificate, e.g. \"rds-ca-rsa2048-g1\"."
  type        = string
  default     = "rds-ca-rsa2048-g1"
}

variable "tags" {
  description = "Tags applied to every resource this module creates."
  type        = map(string)
  default     = {}
}
