app_name: "base"
service_type: "infra"

vpc:
  cidr: "10.0.0.0/16"
  azs: 
    - "ap-southeast-1a"
    - "ap-southeast-1b"
    - "ap-southeast-1c"
  public_subnets:
    - "10.0.0.0/20"
    - "10.0.16.0/20"
    - "10.0.32.0/20"
  private_subnets:
    - "10.0.64.0/18"
    - "10.0.128.0/18"
    - "10.0.192.0/18"
  enable_nat_gateway: true
  single_nat_gateway: true 
  enable_dns_hostnames: true
  enable_dns_support: true
  enable_flow_log: false
  public_subnet_tags:
    Tier: "Public"
    Reachability: "Internet-Facing"
  private_subnet_tags:
    Tier: "Private"
    Reachability: "Internal-Only"