output "vpc_id" { value = module.vpc.vpc_id }
output "vpc_cidr_block" { value = module.vpc.vpc_cidr_block }
output "azs" { value = module.vpc.azs }
output "public_subnets" { value = module.vpc.public_subnets }
output "private_subnets" { value = module.vpc.private_subnets }
output "database_subnets" { value = try(module.vpc.database_subnets, []) }
output "natgw_ids" { value = try(module.vpc.natgw_ids, []) }
output "igw_id" { value = module.vpc.igw_id }
output "public_route_table_ids" { value = module.vpc.public_route_table_ids }
output "private_route_table_ids" { value = module.vpc.private_route_table_ids }
