# ===========================================================================
# DEV
#
# Optimised for iteration cost, not resilience. The differences from prod are
# deliberate and each one is a trade recorded below — this is not "prod with
# smaller numbers".
#
# No secret belongs in this file. The database password is generated by AWS into
# Secrets Manager and never passes through Terraform; the Redis AUTH token is
# referenced by secret ARN. See README "How secrets are handled".
# ===========================================================================

environment = "dev"
region      = "ap-southeast-1"
project     = "platform"
owner       = "platform-engineering"
cost_center = "engineering-dev"

# ---------------------------------------------------------------------------
# Foundation
#
# Environment CIDRs must not overlap: 10.10/10.20/10.30. Overlapping ranges make
# VPC peering and Transit Gateway attachment impossible, and the fix is a
# re-address of a live environment.
# ---------------------------------------------------------------------------

vpc_cidr = "10.10.0.0/16"
az_count = 2

# TRADE: one NAT gateway instead of two. Saves roughly $35/month and makes
# egress a single-AZ dependency. Acceptable here; forced off in prod.
single_nat_gateway = true

enable_flow_logs        = true
flow_log_retention_days = 7

# ---------------------------------------------------------------------------
# Workloads
# ---------------------------------------------------------------------------

enable_alb         = true
enable_eks         = true
enable_ec2         = false
enable_rds         = true
enable_elasticache = false
enable_lambda      = false
enable_ecr         = true

# No domain is managed in dev, so the ALB is reached on its own DNS name over
# HTTP. Turning enable_acm on requires enable_route53 and a zone to validate in.
enable_route53 = false
enable_acm     = false

# ---------------------------------------------------------------------------
# ALB
# ---------------------------------------------------------------------------

alb_internal                   = false
alb_ingress_cidrs              = ["0.0.0.0/0"]
application_port               = 8080
health_check_path              = "/healthz"
alb_access_logs_retention_days = 14

# ---------------------------------------------------------------------------
# EKS
# ---------------------------------------------------------------------------

kubernetes_version = "1.31"

# TRADE: the API endpoint is public, restricted to the office range. Convenient
# for a laptop; prod forces this off and reaches the API from inside the VPC.
eks_public_api_access = true
eks_public_api_cidrs  = ["203.0.113.0/24"] # REPLACE with your office/VPN egress range

eks_node_groups = {
  general = {
    instance_types = ["t3.large"]
    capacity_type  = "SPOT" # TRADE: spot only. Fine for a dev cluster; a prod
    min_size       = 1      # cluster keeps an on-demand floor.
    max_size       = 3
    desired_size   = 2
    disk_size      = 50
  }
}

# ---------------------------------------------------------------------------
# RDS
# ---------------------------------------------------------------------------

rds_engine                = "postgres"
rds_engine_version        = "16.4"
rds_family                = "postgres16"
rds_major_engine_version  = "16"
rds_instance_class        = "db.t4g.medium"
rds_allocated_storage     = 20
rds_max_allocated_storage = 100

# TRADE: single-AZ, 3 days of backups. Losing a dev database costs a re-seed.
rds_multi_az                = false
rds_backup_retention_period = 3

rds_database_name = "appdb"
rds_username      = "dbadmin"

# ---------------------------------------------------------------------------
# ECR
#
# use_name_prefix = false so dev, staging and prod share one repository. An
# image is built once and promoted by digest; a per-environment repository would
# mean rebuilding for each, which is a different artifact each time.
# ---------------------------------------------------------------------------

ecr_use_name_prefix = false

ecr_repositories = {
  api = {
    image_tag_mutability = "IMMUTABLE"
    scan_on_push         = true
    untagged_expiry_days = 3
    keep_tagged_count    = 20
  }
}

# ---------------------------------------------------------------------------
# Observability
# ---------------------------------------------------------------------------

log_retention_days     = 7
create_alarm_dashboard = true

# An email subscription stays PENDING_CONFIRMATION until someone clicks the
# link, and Terraform reports success either way. Confirm it, or use https to
# an on-call system which confirms itself.
alarm_subscriptions = {
  # oncall = { protocol = "https", endpoint = "https://events.pagerduty.com/integration/REPLACE/enqueue" }
}
