alb:
  name: "public-alb"
  target_groups:
    - name: "app-api-tg"
      backend_protocol: "HTTP"
      backend_port: 80
      target_type: "ip"
  http_tcp_listeners:
    - port: 80
      protocol: "HTTP"
      action_type: "forward"
      target_group_index: 0
